### ISSUE TITLE
RSpec / YARD?

### ISSUE THREAD

**Issue by postmodern** [robbyrussell/shorturl#10]
I normally use RSpec and YARD in my projects. Would you be opposed to switching from test-unit to RSpec or RDoc to YARD?

**Comment by robbyrussell** [comment]
+1 for rspec

**Comment by postmodern** [comment]
RSpec shared examples will help me get coverage across all the services. As for YARD, it helps with annotating methods, especially the `@semipublic` and `@private` api tags.
